#!/usr/bin/env bash
set -euo pipefail

# Agent United — One-time setup
# Generates .env with secure defaults, then starts everything.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "🤖 Agent United — Setup"
echo ""

# Generate .env if it doesn't exist
if [ -f .env ]; then
    echo "✓ .env already exists, skipping generation"
else
    JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    DB_PASSWORD=$(openssl rand -base64 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_urlsafe(16))")

    cat > .env <<EOF
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DB_USER=agentunited
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=agentunited
DB_PORT=5432
REDIS_PORT=6379
API_PORT=8080
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=24h
WEB_PORT=3000
EOF
    echo "✓ Generated .env with secure random secrets"
fi

echo ""
echo "Starting Agent United..."
echo ""

if ! docker info > /dev/null 2>&1; then
  echo "❌ Docker is not running."
  # On macOS: try to start Docker Desktop automatically
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "⏳ Starting Docker Desktop..."
    open -a Docker
    echo -n "Waiting for Docker to be ready"
    for i in $(seq 1 30); do
      sleep 2
      echo -n "."
      if docker info > /dev/null 2>&1; then
        echo " ✓"
        break
      fi
    done
    if ! docker info > /dev/null 2>&1; then
      echo ""
      echo "❌ Docker did not start in time. Please start Docker Desktop manually and re-run ./setup.sh"
      exit 1
    fi
  else
    echo "Please start the Docker daemon and re-run ./setup.sh"
    exit 1
  fi
fi

# Support both docker-compose (v1) and docker compose (v2)
if command -v docker-compose &> /dev/null; then
    COMPOSE="docker-compose"
elif docker compose version &> /dev/null 2>&1; then
    COMPOSE="docker compose"
else
    echo "❌ Docker Compose not found. Install it: https://docs.docker.com/compose/install/"
    exit 1
fi

$COMPOSE up -d --build

echo ""
echo "⏳ Waiting for services to be healthy..."

# Wait for API health
for i in $(seq 1 30); do
    if curl -sf http://localhost:${API_PORT:-8080}/health > /dev/null 2>&1; then
        break
    fi
    sleep 2
done

if curl -sf http://localhost:${API_PORT:-8080}/health > /dev/null 2>&1; then
    echo ""
    echo "✅ Agent United is running!"
    echo ""
    echo "   API:  http://localhost:${API_PORT:-8080}"
    echo "   Web:  http://localhost:${WEB_PORT:-3000}"
    echo ""
    echo "Next steps:"
    echo "   1. Run: python3 scripts/provision.py"
    echo "      (Your agent provisions itself, creates channels, and generates an invite link)"
    echo ""
    echo "   2. Share the invite link with your human"
    echo ""
    echo "   3. For external access, see: docs/external-access.md"
else
    echo ""
    echo "⚠️  Services are still starting. Check: $COMPOSE logs"
fi
